### ISSUE TITLE
[Issue]: Release Tags

### ISSUE THREAD

**Issue by trixirt** [ROCm/aotriton#11]
### Problem Description

To be included in Fedora or any distro there must be a releases, they should be consistent with the existing ROCm.
Could we have a 6.0.2 tag and release ?
 

### Operating System

Fedora Rawhide

### CPU

x86_64

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 6.0.0

**Comment by xinyazhang** [comment]
@trixirt AOTriton is delivered independently with ROCM for faster moving pace. We can tag releases but it will named differently (For example, `0.2b` was used during our internal review).

For compatibility against ROCM, AOTriton should be compatible with all ROCM 5+ at source level. Its ABI compatibility depends on the version of ROCM used during its build process.

**Comment by xinyazhang** [comment]
@trixirt Tags created. Please use [0.4b](https://github.com/ROCm/aotriton/releases/tag/0.4b) for the release.

For Github releases we are considering releasing compiled binary blobs as well and it may take extra time. (However I don't think this is a blocking factor for Fedora since it will build from source anyway)

Feel free to reopen this issue if have further questions.
