### ISSUE TITLE
[Feature]: C++ version `mk_aotensor`

### ISSUE THREAD

**Issue by xinji1** [ROCm/aotriton#15]
### Suggestion Description

Thanks for the great work!  I've tried AOTriton and it does help me. however, the function `mk_aotensor()` becomes another blocked overhead for our kernel. Could AOTriton support c++ `mk_aotensor` ? if so, how about the ETA?

In fact i've tried it according to [flash_attn_torch](https://github.com/pytorch/pytorch/blob/d0211e207c78fafac2edaf2e14954f668e898b4a/aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip#L499), but it showes some errors when i try to include `ATen/c10` in the AOTriton building process .

**Comment by xinyazhang** [comment]
The C++ version is left blank intentionally because AOTriton was not designed as a PyTorch-only library, and the TensorView was introduced for a more generic interface, rather than some API tightly coupled with PyTorch and its data types.

However, we do have a C++ version of mk_aotensor, which can be found in PyTorch 2.3's source code tree: https://github.com/pytorch/pytorch/blob/97ff6cfd9c86c5c09d7ce775ab64ec5c99230f5d/aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip#L80-L158

**Comment by xinji1** [comment]
got it. I'll close this issue
