### ISSUE TITLE
[Question] Autotune kernel based on `third_party/triton`

### ISSUE THREAD

**Issue by xinji1** [ROCm/aotriton#21]
Thanks for the great work! a little naive question here, about how to get the best performance with specific inputs.

In triton, we usually apply `autotune` to get the best setting. so it's same for aotriton right?  we need to `triton.autotune` to get the best setting under the specific [third_party/triton](https://github.com/ROCm/triton/tree/9b73a543a5545960bcaf2830900b0560eec443c5), then add it into the `database` ?

**Comment by xinyazhang** [comment]
On the target GPU, run `python tritonsrc/tune_flash.py --db_file v2python/rules/tuning_database.sqlite3` with the input sizes you are aiming to optimize. You can check the arguments supported by this script with `-h`.

Since this script re-uses the autotune mechanism to find out the optimal compiler options, the environment must install the the triton that comes with the AOTriton.

**Comment by xinji1** [comment]
> On the target GPU, run `python tritonsrc/tune_flash.py --db_file v2python/rules/tuning_database.sqlite3` with the input sizes you are aiming to optimize. You can check the arguments supported by this script with `-h`.
> 
> Since this script re-uses the autotune mechanism to find out the optimal compiler options, the environment must install the the triton that comes with the AOTriton.

I c. Looks like we're on the same page. Will close this issue.
