### ISSUE TITLE
[Issue]: How does aotriton handle the fa operator whose batch and n_heads are not the same?

### ISSUE THREAD

**Issue by lzc17** [ROCm/aotriton#60]
### Problem Description

Hello, I want to apply aotriton in the fa operator with different batch and n_heads, but I noticed that the values ​​of batch and n_heads in tune_flash.py that writes to the database are fixed to 1, which means I have to compile two static libraries to ensure the performance of the fa operator. I would like to ask how I should solve this problem.Thank you very much for your answer!

### Operating System

Ubuntu22.04.3

### CPU

AMD Ryzen 9 5900HX

### GPU

MI300X

### ROCm Version

ROCm 6.2.0

**Comment by xinyazhang** [comment]
Hi @lzc17 
Current AOTriton's FA dispatching scheme selects optimal GPU kernels only according to the sequence lengths (`(max_)seqlen_q/k`), batch size and n_heads is not taken into consideration because they are more of a linear scaling up factors to the total number of blocks. The optimal GPU kernel should not change drastically for different batch sizes or number of heads.

In addition, the latest tuning scheme has changed. Since 0.7b we do not operate on the tuning database directly with `tune_flash.py`. It has become a two-step process
1. Run `tune_flash.py` with `--json`, to store the raw experimental results to json file
2. Run `python -m v2python.table_tool`, to process the json file and write the updates to the tuning database.

**Comment by lzc17** [comment]
Can the values ​​of batch size and n_heads be set arbitrarily? When I set them both to 1, the actual test uses different batch sizes and n_heads, and the test performance is lower than the runtime tuning.

**Comment by lzc17** [comment]
![image](https://github.com/user-attachments/assets/7fe36fa8-1e11-49b0-82c2-442b9e2f0057)
The above figure shows the optimal configuration when batch size and n_heads are different. The two are obviously different, and the actual performance gap is also very large.

**Comment by xinyazhang** [comment]
> Can the values ​​of batch size and n_heads be set arbitrarily?

Yes they can, but usually I'm using 4/12 and reduce to 2/2 when reaching memory limits.

> The above figure shows the optimal configuration when batch size and n_heads are different

Can you post the raw performance numbers (can be found in the `--json_file` output as `time`)?

If they do have very significant performance differences, the dispatcher will need some changes in order to support it (targeting 0.9b)
(Yeah current dispatcher itself already supports adding more tuning factors than existing `seqlen_q` and `seqlen_k`, but utilities need updates)

**Comment by lzc17** [comment]
The json file cannot be provided here because it is modified from the tune_flash.py file in version 0.6b. In addition， I would also like to ask if the reverse version of 0.6b does not support tuning with a larger config range? In the 0.6b version, increasing the reverse config will result in an error of address out-of-bounds access.

**Comment by lzc17** [comment]
After testing, the forward running times of the two optimal configurations are 39.95ms and 38.30ms respectively.

**Comment by xinyazhang** [comment]
> I would also like to ask if the reverse version of 0.6b does not support tuning with a larger config range?

Larger configs require larger VRAM, and it is not supported due to hardware limits. The current solution is to reduce the `BATCH` and `N_HEADS`
https://github.com/ROCm/aotriton/blob/016f733e8ff746450e066f78bed68709ccd93e60/test/tune_flash.py#L72-L77

(Note we refactored the testing suite significantly in 0.7)

> will result in an error of address out-of-bounds access

This is due to memory allocation error caused by OOM. Consequently some tensor pointers are invalid.

**Comment by lzc17** [comment]
Thanks for your answer, I will close this issue。
