### ISSUE TITLE
[Issue]: The reason why the bwd kernel is not fused

### ISSUE THREAD

**Issue by lzc17** [ROCm/aotriton#62]
### Problem Description

There is code in the reverse kernel code repository to fuse the two operators dk_dv and dq, but it is not enabled. I want to know the reason. Is it because the performance is not as good as the current implementation, or is there a problem with the fusion code itself?

### Operating System

Ubuntu22.04.3

### CPU

AMD Ryzen 9 5900HX

### GPU

MI300X

### ROCm Version

ROCm 6.3.0, ROCm 6.2.4

**Comment by xinyazhang** [comment]
The removal is for code cleanup. The removed fused kernel is not well-tested nor well-optimized, and thus its performance is also 
The fused kernel approach is more like a new feature due to its considerable effort to do it right and then do it fast.

They'll be back once we have better understanding of fused kernel performances.
